export const qaData = [
  { id: "js-1",   q: "What is closure in JavaScript?",
    a: "A closure is a function that has access to variables from its outer scope even after the outer function has returned.",
    category: "javascript", difficulty: "intermediate" },
  { id: "js-2",   q: "What is the difference between let and var?",
    a: "let is block-scoped and not hoisted, while var is function-scoped and hoisted to the top of its function.",
    category: "javascript", difficulty: "beginner" },
  { id: "js-3",   q: "What is event delegation?",
    a: "Event delegation attaches a single event listener to a parent element to handle events from child elements using event bubbling.",
    category: "javascript", difficulty: "intermediate" },
  { id: "js-4",   q: "What is the prototype chain?",
    a: "The prototype chain is JavaScript's inheritance mechanism where objects inherit properties from their prototype object.",
    category: "javascript", difficulty: "advanced" },
  { id: "js-5",   q: "What is Promise.all?",
    a: "Promise.all takes an array of promises and resolves when all resolve, or rejects if any one fails.",
    category: "javascript", difficulty: "intermediate" },
  { id: "node-1", q: "What is the event loop in Node.js?",
    a: "The event loop processes callbacks from the event queue when the call stack is empty, enabling async operations.",
    category: "nodejs", difficulty: "intermediate" },
  { id: "node-2", q: "What is middleware in Express?",
    a: "Middleware are functions that execute during the request-response cycle with access to req, res, and next.",
    category: "nodejs", difficulty: "beginner" },
  { id: "node-3", q: "What are streams in Node.js?",
    a: "Streams process data in chunks continuously, useful for large files without loading everything into memory.",
    category: "nodejs", difficulty: "intermediate" },
  { id: "node-4", q: "What is clustering in Node.js?",
    a: "Clustering creates child processes sharing the same port, utilizing all CPU cores for better performance.",
    category: "nodejs", difficulty: "advanced" },
  { id: "node-5", q: "What is the difference between process.nextTick and setImmediate?",
    a: "process.nextTick fires before I/O events in current iteration, setImmediate fires in check phase after I/O.",
    category: "nodejs", difficulty: "advanced" },
  { id: "db-1",   q: "What is the difference between SQL and NoSQL?",
    a: "SQL uses structured tables with fixed schemas, NoSQL uses flexible document or key-value structures.",
    category: "database", difficulty: "beginner" },
  { id: "db-2",   q: "What is database indexing?",
    a: "Indexing creates a data structure that improves query speed without scanning the entire table.",
    category: "database", difficulty: "intermediate" },
  { id: "db-3",   q: "What is Redis used for?",
    a: "Redis is an in-memory store used for caching, session management, pub/sub, and rate limiting.",
    category: "database", difficulty: "beginner" },
  { id: "db-4",   q: "What is database sharding?",
    a: "Sharding is horizontal partitioning of data across multiple database instances to distribute load.",
    category: "database", difficulty: "advanced" },
  { id: "db-5",   q: "What is an ORM?",
    a: "ORM lets you query and manipulate database data using object-oriented programming instead of raw SQL.",
    category: "database", difficulty: "beginner" },
  { id: "sec-1",  q: "What is SQL injection?",
    a: "SQL injection inserts malicious SQL into queries, allowing attackers to access or modify database data.",
    category: "security", difficulty: "beginner" },
  { id: "sec-2",  q: "What is JWT?",
    a: "JWT is a compact token for stateless authentication, containing encoded user info and a signature.",
    category: "security", difficulty: "intermediate" },
  { id: "sec-3",  q: "What is CORS?",
    a: "CORS controls which domains can make requests to your API as a browser security mechanism.",
    category: "security", difficulty: "intermediate" },
  { id: "sec-4",  q: "What is bcrypt?",
    a: "bcrypt is a password hashing function that adds salt and uses multiple rounds against brute-force attacks.",
    category: "security", difficulty: "intermediate" },
  { id: "sec-5",  q: "What is rate limiting?",
    a: "Rate limiting restricts requests per time window to prevent abuse, DDoS attacks, and ensure fair usage.",
    category: "security", difficulty: "beginner" },
  { id: "perf-1", q: "What is caching?",
    a: "Caching stores frequently accessed data in fast memory to reduce database load and improve response times.",
    category: "performance", difficulty: "beginner" },
  { id: "perf-2", q: "What is lazy loading?",
    a: "Lazy loading defers loading resources until needed, improving initial load time and reducing memory usage.",
    category: "performance", difficulty: "intermediate" },
  { id: "perf-3", q: "What is connection pooling?",
    a: "Connection pooling maintains reusable database connections to avoid overhead of creating new ones per request.",
    category: "performance", difficulty: "intermediate" },
  { id: "perf-4", q: "What is load balancing?",
    a: "Load balancing distributes requests across multiple servers to prevent overload and ensure high availability.",
    category: "performance", difficulty: "intermediate" },
  { id: "perf-5", q: "What is CDN?",
    a: "CDN serves static assets from servers close to users, reducing latency and improving load times.",
    category: "performance", difficulty: "beginner" },
];
